services:
  - type: web
    name: contour
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # Use this for production
    # startCommand: "python app.py"   # Use this for development
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0